application: mindale-com
#module: default
version: v1
runtime: go
api_version: go1
threadsafe: true
#instance_class: F1

#automatic_scaling:
#  min_idle_instances: 1
#  max_pending_latency: 1s


handlers:

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  secure: optional
  

- url: /static
  static_dir: static

- url: /img
  static_dir: img  


- url: /css
  static_dir: css


- url: /js
  static_dir: js    
  
- url: /.*
  script: _go_app


# Important! Even though there's a catch all routing above,
# without these two lines it's not going to work.
# Make sure you have this:
#- url: /_ah/spi/.*
#  script: _go_app
