application: cometiphrd
version: v1
runtime: go
api_version: go1
threadsafe: true

default_expiration: "1s"

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$

handlers:

- url: /favicon.ico
  static_files: static/favicon.ico
  upload:  static/favicon.ico

- url: /templates
  static_dir: templates
  application_readable: true

- url: /static
  static_dir: static

- url: /.*
  script: _go_app
